blueprints/user_blueprint.py
from db.DB import DB
from flask import (Blueprint, redirect, render_template, request, session,
                   url_for)

from models.user import User

user_services = Blueprint("user_services", __name__)
mydb = DB.connect()


@user_services.route('/login', methods=['GET'])
def login_page():
    if 'username' in session:
        return redirect(url_for('employee_services.index'))
    msg = ''
    return render_template('login.html', msg=msg)


@user_services.route('/login', methods=['POST'])
def login():
    msg = ''
    if 'username' in request.form and 'password' in request.form:
        username = request.form['username']
        password = request.form['password']

        is_username = DB.select_query(
            'SELECT COUNT(username) FROM user WHERE username = %s', (username,))
        is_username = is_username[0]['COUNT(username)']

        if is_username == 1:
            stored_password = DB.select_query(
                'SELECT password FROM user WHERE username = %s', (username,))
            stored_password = stored_password[0]['password']

            if User.verify_password(stored_password, password):
                session['loggedin'] = True
                session['username'] = username
                return redirect(url_for('employee_services.index'))
            else:
                msg = 'Username and/or password is not correct!'
                return render_template('login.html', msg=msg)
        else:
            msg = 'Username and/or password is not correct!'
            return render_template('login.html', msg=msg)
    else:
        msg = 'Check your details, and try to login again!'
        return render_template('login.html', msg=msg)

templates/index.html
{% extends "layout.html" %}
{% block body %}
{% if 'username' in session %}
  <div class="row p-2 ">
    <h3>Employees</h3>
  </div>
  <table id="example" class="table table-striped table-bordered custom-table">
    <thead>
      <tr>
        <td>ID</td>
        <td>First name</td>
        <td>Last name</td>
        <td>Order</td>
        <td>LinkedIn</td>
        <td>Xing</td>
        <td>Role</td>
        <td>Email</td>
        <td>Photo</td>
        <td colspan="2">Actions</td>
      </tr>
    </thead>
    <tbody>
      {% for row in list_employees %}
      <tr>
        <td>{{row.get_id()}}</td>
        <td>{{row.get_firstName()}}</td>
        <td>{{row.get_lastName()}}</td>
        <td>{{row.get_order()}}</td>
        <td>{{row.get_linkedIn()}}</td>
        <td>{{row.get_xing()}}</td>
        <td>{{row.get_role()}}</td>
        <td>{{row.get_email()}}</td>
        <td class="photoHolder">
          <img src="{{row.get_pohotUrl()}}" alt="">
        </td>
        <td width="120">
          <form action="/employees/delete/{{row.get_id()}}" method="post">
            <input class="btn btn-danger btn-delete btn-sm" type="submit" value="Delete">
          </form>
        </td>
        <td>
          <a href="/employees/update/{{row.get_id()}}" class=" btn-sm btn btn-success">Update</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="row">
    <div class="col-md-4">
      {% with messages = get_flashed_messages() %}
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">x</span>
        </button>
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}

    </div>
  </div>
  </div>
{% endif %}
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title></title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"
    id="bootstrap-css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
  <link rel="stylesheet" href="{{url_for('static', filename= 'style/style.css')}}">
</head>

<body>
  {% include "navbar.html" %}
  <div class="container pt-4">
    {% block body %}
    {% endblock %}
  </div>

  <script>
    const btnDelete = document.querySelectorAll('.btn-delete');
    if (btnDelete) {
      const btnArray = Array.from(btnDelete);
      btnArray.forEach((btn) => {
        btn.addEventListener('click', (e) => {
          if (!confirm('Are you sure you want to delete employee ?')) {
            e.preventDefault();
          }
        });
      })
    }
  </script>
</body>

</html>

templates/login.html
{% extends "layout.html" %}
{% block body %}
	<div>
		<form action="{{ url_for('user_services.login') }}" method="post" class="form">
			<div class="form-group">
			<p>
				<label for="username">Username</label>
				<input type="text" class="form-control" name="username" placeholder="Username" id="username" required>
			</p>
			<p>
				<label for="password">Password</label>
				<input type="password" class="form-control" name="password" placeholder="Password" id="password" required>
				<div>{{ msg }}</div>
			</p>
			<p class="d-flex justify-content-center">
				<input type="submit" class="btn btn-primary" value="Login">
			</p>
			</div>
		</form>
	</div>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav">

      {% if 'username' in session %}
      <li class="nav-item">
          <a class="nav-link" href="/employees/">Dashboard</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="/employees/register">Register</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="/employees/logout">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
          <a disabled class="nav-link">Admin panel</a>
      </li>
      {% endif %}
    </ul>
  </nav>

templates/register.html
{% extends "layout.html" %}
{% block body %}

<div id="header">
    <h3>Register</h3>
</div>
<div id="main">
    <div id="main_form">
        <form action="/employees/register" class="form" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <p>
                    <label for="firstName">First name:</label>
                    <input type="text" name="firstName" id="firstName" required class="form-control" value="{{firstName}}">
                </p>
                <p>
                    <label for="lastName">Last name: </label>
                    <input type="text" name="lastName" id="lastName" required class="form-control" value="{{lastName}}">
                </p>
                <p>
                    <label for="order">Order: </label>
                    <input type="number" min="1" name="order" id="order" required class="form-control" value="{{order}}">
                </p>
                <p>
                    <label for="linkedIn">LinkedIn: </label>
                    <input type="text" name="linkedIn" id="linkedIn" class="form-control" value="{{linkedIn}}">
                </p>
                <p>
                    <label for="xing">Xing: </label>
                    <input type="text" name="xing" id="xing" class="form-control" value="{{xing}}">
                </p>
                <p>
                    <label for="role">Role: </label>
                    <input type="text" name="role" id="role" class="form-control" value="{{role}}">
                </p>
                <p>
                    <label for="email">Email: </label>
                    <input type="email" name="email" pattern= ".+@.+\..+" id="email"  placeholder="johndoe@example.com" required class="form-control" value="{{email}}">
                    <span class="text-danger">{{email_error}}</span>
                </p>
                <p>
                    <label for="photoUrl">Photo: </label>
                    <input type="file" accept="image/*" name="photoUrl" id="photoUrl" onchange="PreviewImage();" class="form-control">
                    <div class="photoHolder photoHolder-x">
                        <span>{{file_error}}</span>
                        <img id="uploadPreview">
                    </div>
                </p>
                <p>
                    <input type="submit" value="Register" class="btn btn-success form-control">
                </p>
            </div>
        </form>
    </div>
</div>


<script>
    function PreviewImage() {
        var oFReader = new FileReader();
        oFReader.readAsDataURL(document.getElementById("photoUrl").files[0]);

        oFReader.onload = function (oFREvent) {
            document.getElementById("uploadPreview").src = oFREvent.target.result;
            document.querySelector('.photoHolder').classList.add('photo-x')
            document.querySelector('#uploadPreview').classList.remove('hide');
        };
    };

    document.querySelector('.photoHolder-x').addEventListener('click', function () {
        document.getElementById("photoUrl").value = '';
        document.querySelector('#uploadPreview').classList.add('hide');
        document.querySelector('.photoHolder-x').classList.remove('photo-x')
    });
    

</script>

{% endblock %}

templates/update.html
{% extends "layout.html" %}
{% block body %}
<div id="header">
    <h3>Update</h3>
</div>
<div id="main">
    <div id="main_form">
        <form action="/employees/update/{{employee.get_id()}}" class="form" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <p>
                    <label for="firstName">First name: </label>
                    <input type="text" name="firstName" id="firstName" value="{{employee.get_firstName()}}" required
                        class="form-control">
                </p>
                <p>
                    <label for="lastName">Last name: </label>
                    <input type="text" name="lastName" id="lastName" value="{{employee.get_lastName()}}" required
                        class="form-control">
                </p>
                <p>
                    <label for="order">Order: </label>
                    <input type="number" name="order" min="1" id="order" value="{{employee.get_order()}}" required
                        class="form-control">
                </p>
                <p>
                    <label for="linkedIn">LinkedIn: </label>
                    <input type="text" name="linkedIn" id="linkedIn" value="{{employee.get_linkedIn()}}"
                        class="form-control">
                </p>
                <p>
                    <label for="xing">Xing: </label>
                    <input type="text" name="xing" id="xing" value="{{employee.get_xing()}}" class="form-control">
                </p>
                <p>
                    <label for="role">Role: </label>
                    <input type="text" name="role" id="role" value="{{employee.get_role()}}" class="form-control">
                </p>
                <p>
                    <label for="email">Email: </label>
                    <input type="email" name="email" id="email" pattern=".+@.+\..+" placeholder="johndoe@example.com" value="{{employee.get_email()}}"
                        class="form-control" required>
                    <span>{{email_error}}</span>
                </p>
                <p>
                    <label for="photoUrl">Photo: </label>
                    <input type="file" accept="image/*" name="photoUrl" id="photoUrl" class="form-control"
                        value="{{employee.get_pohotUrl()}}" {% if employee.get_pohotUrl() == "" %} class="hide"  {% endif %} >

                    <input type="number"  name="deletePhoto" id="deletePhoto" class="form-control hide"
                        value="0">

                <div class="photoHolder photoHolder-x">
                    <span id="file_error">{{file_error}}</span>
                    <img class="image" id="image" src="{{employee.get_pohotUrl()}}" alt="">
                </div>
            
                </p>
                <p>
                    <input type="submit" value="Update" class="btn btn-success form-control">
                </p>
            </div>
        </form>
    </div>
</div>
<script>
    document.getElementById('photoUrl').onchange = function () {
        let src = URL.createObjectURL(this.files[0]);
        document.getElementById('image').src = src;
        document.querySelector('.photoHolder').classList.add('photo-x');
        document.querySelector('.image').classList.remove('hide');
    }
    

    let img = document.getElementById('image');
    let src = img.getAttribute('src');
    
    if (src) {
       document.querySelector('.photoHolder-x').classList.add('photo-x');
    }


    document.querySelector('.photoHolder-x').addEventListener('click', function () {
        
        document.getElementById('deletePhoto').value = 1;
        img.classList.add('hide');
        document.querySelector('.photoHolder-x').classList.remove('photo-x');
    });
    

</script>

{% endblock %}